version: '3'
services:
  # This service loads in data from the GitHub Archive project at
  # a specified rate.
  archive_streamer:
    build: archive_streamer
    # We only speed up by around 8x here to avoid overloading
    # our single Kafka node. It seems to handle this on most
    # systems but you can ajust that up or down.
    command: "python /code/stream.py --speedup 24 --kafka kafka:9092"
    links:
      - kafka
  # This dashboard serves as a example of the output we generate.
  # It's minimal and mostly for demonstration purposes but can
  # be extended or swapped out for something else. We connect to
  # Kafka directly here.
  dashboard:
    build: dashboard
    command: python /code/dashboard.py
    ports:
      # Flask Web UI
      - "127.0.0.1:5000:5000"
    links: []
  # The primary instance of the star_leaders wallaroo app
  # is also known as the initializer. This instance will
  # be responsible for managing the clusters when other
  # worker nodes join.
  wallaroo_primary_worker:
    build: star_leaders
    command: bash /code/primary.sh
    privileged: true
    ports:
      # cluster control channel port
      - "12500:12500"
      # cluster data channel port
      - "12501:12501"
      # external control port
      - "5050:5050"
    links:
      - wallaroo_metrics_ui
  # Secondary instances allow us to expand work to other
  # machines, or for CPython other cores to get around the
  # limitations of the GIL. We only start one for illustration.
  wallaroo_secondary_worker:
    build: star_leaders
    command: bash /code/secondary.sh
    privileged: true
    links:
      - wallaroo_metrics_ui
      # We'd like to have a link to the primary worker
      # in order to initialize this worker node.
      - wallaroo_primary_worker
  # Setup the Metrics UI so we can watch our application performance
  wallaroo_metrics_ui:
    image: wallaroo-labs-docker-wallaroolabs.bintray.io/release/metrics_ui:0.4.2
    ports:
      # The web UI
      - "4000:4000"
      # Metrics collection port
      - "5001:5001"
